WebShopClient/ViewComponents/ShoppingCartSummaryViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using WebShopClient.Services;

namespace WebShopClient.ViewComponents
{
    public class ShoppingCartSummaryViewComponent : ViewComponent
    {
        private readonly ShoppingCartService _shoppingCartService;

        public ShoppingCartSummaryViewComponent(ShoppingCartService shoppingCartService)
        {
            _shoppingCartService = shoppingCartService;
        }

        public IViewComponentResult Invoke()
        {
            var cartItems = _shoppingCartService.GetCartItems();
            var productsInCart = cartItems.Sum(item => item.Quantity);
            return View(productsInCart);
        }
    }
}

WebShopClient/Views/Shared/_AuthHeaderListItems.cshtml
@using System.Security.Claims

@{
    if (User.Identity.IsAuthenticated)
    {
        var roleClaim = User.FindFirst(ClaimTypes.Role);

        if (roleClaim.Value == "Admin")
        {
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle text-dark" href="#" id="adminDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                    Admin
                </a>
                <ul class="dropdown-menu" aria-labelledby="adminDropdown">
                    <li><a class="dropdown-item" asp-area="" asp-controller="Admin" asp-action="Dashboard">Dashboard</a></li>
                    <li><a class="dropdown-item" asp-area="" asp-controller="Admin" asp-action="ManageProducts">Manage Products</a></li>
                    <li><a class="dropdown-item" asp-area="" asp-controller="CustomerManagement" asp-action="Index">Customers</a></li>                                    
                    <li><a class="dropdown-item" asp-area="" asp-controller="Admin" asp-action="GetOrders">Orders</a></li>
                </ul>
            </li>
        }
        
        <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle text-dark" href="#" id="user-dropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                My Account
            </a>
            <ul class="dropdown-menu" aria-labelledby="user-dropdown">
                <a class="nav-link" asp-controller="Customers" asp-action="Orders">My Orders</a>
                <a class="nav-link" asp-controller="Customers" asp-action="Logout">Logout</a>
            </ul>
        </li>
    }
    else
    {
        <a class="nav-link" asp-area="" asp-controller="Customers" asp-action="Login">Login</a>
    }
}

WebShopClient/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Web Shop</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/WebShopClient.styles.css" asp-append-version="true" />
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;700&display=swap" rel="stylesheet">

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm border-bottom mb-3">
            <div class="container-fluid px-4">
                <div class="d-flex justify-content-between align-items-center w-100">
                    <a class="navbar-brand d-flex align-items-center" asp-area="" asp-controller="Home" asp-action="Index">
                        <img class="me-1" src="@(Url.Content("~/smile.svg"))" />HAPPY TIMES
                    </a>
                    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                </div>
                <div class="collapse navbar-collapse" id="navbarNav">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                        <!-- Removed the Home link from here -->
                    </ul>
                    <ul class="navbar-nav ms-auto d-flex align-items-center">
                        <li class="nav-item">
                            <form class="d-flex position-relative" style="width:200px" role="search">
                                <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search" id="searchInput" autocomplete="off">
                                <div class="search-results" id="searchResults" style="display: none;"></div>
                            </form>
                        </li>
                        @{
                            await Html.RenderPartialAsync("_AuthHeaderListItems");
                        }
                        <li class="nav-item">
                            @await Component.InvokeAsync("ShoppingCartSummary")
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>



    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
	    <div class="container text-center">
            &copy; 2024 - HAPPY TIMES
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    <script>
        $(document).ready(function () {
            $('#searchInput').on('input', function () {
                var query = $(this).val();
                if (query.length > 0) {
                    $.ajax({
                        url: '/Products/Search',
                        type: 'GET',
                        data: { searchString: query },
                        success: function (data) {
                            var results = $('#searchResults');
                            results.empty();
                            if (data.length > 0) {
                                data.forEach(function (product) {
                                    results.append(`
                                                     <div class="result-item d-flex align-items-center" onclick="location.href='/Products/Details/${product.id}'">
                                                     <img src="/uploads/${product.fileName}" alt="Product Image" onerror="this.src='https://i.ibb.co/qpB9ZCZ/placeholder.png'" style="width: 50px; height: 50px; object-fit: cover;">
                                                     <div>
                                                     <div>${product.name}</div>
                                                     <div class="text-danger">${product.price} kr</div>
                                                     </div>
                                                     </div>
                                                    `);
                                });
                            } else {
                                results.append('<div class="result-item">No product found</div>');
                            }
                            results.show();
                        },
                        error: function () {
                            $('#searchResults').hide();
                        }
                    });
                } else {
                    $('#searchResults').hide();
                }
            });

            // döljer sökresultat när man klickar utanför sökrutan
            $(document).on('click', function (event) {
                if (!$(event.target).closest('#searchInput').length && !$(event.target).closest('#searchResults').length) {
                    $('#searchResults').hide();
                }
            });
        });
    </script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>